### ISSUE TITLE
dinghy_http_proxy prevents clean shutdown of docker-compose v2 project

### ISSUE THREAD

**Issue by dannynimmo** [codekitchen/dinghy#236]
**Steps to reproduce**
1. Create a `docker-compose.yml` file with the contents:
```yml
version: '2'
services:
  nginx:
    image: nginx:latest
```
2. run `docker-compose up -d` followed by `docker-compose down`

**Expected behaviour**
Docker containers & network are shut down & removed cleanly

**Actual behaviour**
Error when docker tries to remove the network:

```
$ docker-compose down
Stopping test_nginx_1 ... done
Removing test_nginx_1 ... done
Removing network test_default
ERROR: network test_default has active endpoints
```

Only after manually disconnecting the proxy container from the network (`docker network disconnect test_default dinghy_http_proxy`) can you successfully shut down the project.

**Comment by codekitchen** [comment]
What version of Dinghy? This was recently fixed in version 4.5.0, released just a few days ago.

**Comment by dannynimmo** [comment]
@codekitchen I just upgraded to 4.5.0 but am still experiencing this.

Interestingly though, it seems like some kind of race condition, as I get the error `ERROR: network test_default has active endpoints`, but then running `docker-compose down` again straight away will actually work.

**Comment by codekitchen** [comment]
Yeah, the best solution I could come up with Dinghy-side does have a race condition, see the discussion on the original ticket: https://github.com/codekitchen/dinghy/issues/218

I'm a bit surprised you hit it so immediately though, we've had a lot of luck with the solution. To verify you're on the right proxy version, what's the output of `docker inspect dinghy_http_proxy -f  '{{.Image}}'` ? it should be `sha256:2307d1b836244398e4d15056e3e6017a34513adbd727ca3a26dc38c1778bd1f5`

**Comment by dannynimmo** [comment]
Yep:
```shell
$ docker inspect dinghy_http_proxy -f '{{.Image}}'
sha256:2307d1b836244398e4d15056e3e6017a34513adbd727ca3a26dc38c1778bd1f5
```

It's no major problem, I can just change my scripts to run `stop` then `down` as per the previous ticket. It's weird that I'm hitting it every time though if, like you said, you've had reasonable luck with the timing.

**Comment by codekitchen** [comment]
Ah dang, yeah that's too bad. Sadly without a way to hook into docker-compose, running `stop` first is my best suggestion. I'll close this.
